name: SpawnInvis
main: SpawnInvis\Main
version: 1.0.0
api: 1.13.1
description: This plugin makes players within the spawn radius invisable without particles
author: jasonwynn10

commands:
  invis:
    usage: "/invis"
    description: ""
    permission: invis.toggle
  pinvis:
    usage: "/pinvis"
    description: ""
    permission: pinvis.toggle
    
    permissions:
    invis.toggle:
      default: op
      description: ""
    pinvis.toggle:
      default: true
      description: ""
