name: SpawnInvis
main: SpawnInvis\Main
version: 1.0.0
api: 1.13.1
description: "In a set spawn radius, players will be automatically invisable."
commands:
    invis:
        description: "Toggles Spawn Invisability"
        permission: invis.toggle
        usage: "/invis"
    pinvis:
        description: "sets specific player's invisability in spawn"
        permission: pinvis.toggle
        usage: "/pinvis"
permissions:
    invis.toggle:
        usage: "/invis"
        description: "Toggles Spawn Invisability"
    pinvis.toggle:
        usage: "/pinvis"
        description: "Toggles Specific Player's Invisability"